source 'https://rubygems.org'

# Rails dependencies
gem 'rails', '~> 6.1.4'
gem 'sqlite3', '~> 1.4'

# Other gems
gem 'rack-cors', '~> 1.1', require: 'rack/cors'

group :development, :test do
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :test do
  gem 'minitest', '~> 5.14'
  gem 'rails-controller-testing', '~> 1.0'
  gem 'shoulda-matchers', '~> 4.5'
end

